version: '2'

services:
  st-pyt:
    expose:
      - "8050"
    ports:
      - "8050:8050"
    image: mustafaglr/kafka-log-dashboard:latest
    networks:
      - server-net

networks:
  server-net:
    driver: bridge


